### ISSUE TITLE
Socket.io error

### ISSUE THREAD

**Issue by simonyeldon** [elving/brunch-with-hipsters#1]
I followed the Vanilla instructions, with the Brunch skeleton checkout, but I am getting errors and a white screen.

The error I get is

```
Hipster.Socket = io.connect('http://localhost');
Uncaught ReferenceError: io is not defined 
```

I dug a little deeper and it seems that Socket.io is not installed or included. I added it to the package.json but it didnt help.

Where am I going wrong?

**Comment by elving** [comment]
The problem is that code from the express-socket.io branch ended up in the master branch because of a bad merge (git noob lol). It should be fixed now.

**Comment by simonyeldon** [comment]
Thanks for that, I dont get any javascript errors, but I am still getting a white screen....

**Comment by elving** [comment]
Yeah, this skeleton doesn't have any example views/templates/styles. If you want to see an example of how to use the skeleton take a look at https://github.com/elving/Hackerank
